apiVersion: v1
kind: Service
metadata:
  name: capstone-project-cloud-devops
  labels:
    app: capstone-project-cloud-devops
spec:
  type: LoadBalancer
  selector:
    app: capstone-project-cloud-devops
  ports:
    - port: 80
      targetPort: 80
